//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlarmDisplay.ScadaCoreAlarmDisplayReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tag", Namespace="http://schemas.datacontract.org/2004/07/ScadaCoreWCF.models")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AlarmDisplay.ScadaCoreAlarmDisplayReference.DigitalInput))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AlarmDisplay.ScadaCoreAlarmDisplayReference.AnalogInput))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AlarmDisplay.ScadaCoreAlarmDisplayReference.DigitalOutput))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AlarmDisplay.ScadaCoreAlarmDisplayReference.AnalogOutput))]
    public partial class Tag : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IO_AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IO_Address {
            get {
                return this.IO_AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.IO_AddressField, value) != true)) {
                    this.IO_AddressField = value;
                    this.RaisePropertyChanged("IO_Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Value {
            get {
                return this.ValueField;
            }
            set {
                if ((this.ValueField.Equals(value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DigitalInput", Namespace="http://schemas.datacontract.org/2004/07/ScadaCoreWCF.models")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AlarmDisplay.ScadaCoreAlarmDisplayReference.AnalogInput))]
    public partial class DigitalInput : AlarmDisplay.ScadaCoreAlarmDisplayReference.Tag {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AlarmDisplay.ScadaCoreAlarmDisplayReference.DriverType DriverField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ScanOnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ScanTimeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AlarmDisplay.ScadaCoreAlarmDisplayReference.DriverType Driver {
            get {
                return this.DriverField;
            }
            set {
                if ((this.DriverField.Equals(value) != true)) {
                    this.DriverField = value;
                    this.RaisePropertyChanged("Driver");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ScanOn {
            get {
                return this.ScanOnField;
            }
            set {
                if ((this.ScanOnField.Equals(value) != true)) {
                    this.ScanOnField = value;
                    this.RaisePropertyChanged("ScanOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ScanTime {
            get {
                return this.ScanTimeField;
            }
            set {
                if ((this.ScanTimeField.Equals(value) != true)) {
                    this.ScanTimeField = value;
                    this.RaisePropertyChanged("ScanTime");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AnalogInput", Namespace="http://schemas.datacontract.org/2004/07/ScadaCoreWCF.models")]
    [System.SerializableAttribute()]
    public partial class AnalogInput : AlarmDisplay.ScadaCoreAlarmDisplayReference.DigitalInput {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AlarmDisplay.ScadaCoreAlarmDisplayReference.Alarm[] AlarmsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double HighLimitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LowLimitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnitsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AlarmDisplay.ScadaCoreAlarmDisplayReference.Alarm[] Alarms {
            get {
                return this.AlarmsField;
            }
            set {
                if ((object.ReferenceEquals(this.AlarmsField, value) != true)) {
                    this.AlarmsField = value;
                    this.RaisePropertyChanged("Alarms");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double HighLimit {
            get {
                return this.HighLimitField;
            }
            set {
                if ((this.HighLimitField.Equals(value) != true)) {
                    this.HighLimitField = value;
                    this.RaisePropertyChanged("HighLimit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double LowLimit {
            get {
                return this.LowLimitField;
            }
            set {
                if ((this.LowLimitField.Equals(value) != true)) {
                    this.LowLimitField = value;
                    this.RaisePropertyChanged("LowLimit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Units {
            get {
                return this.UnitsField;
            }
            set {
                if ((object.ReferenceEquals(this.UnitsField, value) != true)) {
                    this.UnitsField = value;
                    this.RaisePropertyChanged("Units");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DigitalOutput", Namespace="http://schemas.datacontract.org/2004/07/ScadaCoreWCF.models")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AlarmDisplay.ScadaCoreAlarmDisplayReference.AnalogOutput))]
    public partial class DigitalOutput : AlarmDisplay.ScadaCoreAlarmDisplayReference.Tag {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double InitialValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double InitialValue {
            get {
                return this.InitialValueField;
            }
            set {
                if ((this.InitialValueField.Equals(value) != true)) {
                    this.InitialValueField = value;
                    this.RaisePropertyChanged("InitialValue");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AnalogOutput", Namespace="http://schemas.datacontract.org/2004/07/ScadaCoreWCF.models")]
    [System.SerializableAttribute()]
    public partial class AnalogOutput : AlarmDisplay.ScadaCoreAlarmDisplayReference.DigitalOutput {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double HighLimitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LowLimitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnitsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double HighLimit {
            get {
                return this.HighLimitField;
            }
            set {
                if ((this.HighLimitField.Equals(value) != true)) {
                    this.HighLimitField = value;
                    this.RaisePropertyChanged("HighLimit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double LowLimit {
            get {
                return this.LowLimitField;
            }
            set {
                if ((this.LowLimitField.Equals(value) != true)) {
                    this.LowLimitField = value;
                    this.RaisePropertyChanged("LowLimit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Units {
            get {
                return this.UnitsField;
            }
            set {
                if ((object.ReferenceEquals(this.UnitsField, value) != true)) {
                    this.UnitsField = value;
                    this.RaisePropertyChanged("Units");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DriverType", Namespace="http://schemas.datacontract.org/2004/07/ScadaCoreWCF.models")]
    public enum DriverType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SimDriver = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RealTimeDriver = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Alarm", Namespace="http://schemas.datacontract.org/2004/07/ScadaCoreWCF.models")]
    [System.SerializableAttribute()]
    public partial class Alarm : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LimitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PriorityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AlarmDisplay.ScadaCoreAlarmDisplayReference.AlarmType TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Limit {
            get {
                return this.LimitField;
            }
            set {
                if ((this.LimitField.Equals(value) != true)) {
                    this.LimitField = value;
                    this.RaisePropertyChanged("Limit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Priority {
            get {
                return this.PriorityField;
            }
            set {
                if ((this.PriorityField.Equals(value) != true)) {
                    this.PriorityField = value;
                    this.RaisePropertyChanged("Priority");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AlarmDisplay.ScadaCoreAlarmDisplayReference.AlarmType Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AlarmType", Namespace="http://schemas.datacontract.org/2004/07/ScadaCoreWCF.models")]
    public enum AlarmType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LOW = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HIGH = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ScadaCoreAlarmDisplayReference.IDatabaseManager", SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IDatabaseManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManager/Registration", ReplyAction="http://tempuri.org/IDatabaseManager/RegistrationResponse")]
        bool Registration(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManager/Registration", ReplyAction="http://tempuri.org/IDatabaseManager/RegistrationResponse")]
        System.Threading.Tasks.Task<bool> RegistrationAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManager/Login", ReplyAction="http://tempuri.org/IDatabaseManager/LoginResponse")]
        string Login(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManager/Login", ReplyAction="http://tempuri.org/IDatabaseManager/LoginResponse")]
        System.Threading.Tasks.Task<string> LoginAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManager/Logout", ReplyAction="http://tempuri.org/IDatabaseManager/LogoutResponse")]
        bool Logout(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManager/Logout", ReplyAction="http://tempuri.org/IDatabaseManager/LogoutResponse")]
        System.Threading.Tasks.Task<bool> LogoutAsync(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManager/TagNameAvailable", ReplyAction="http://tempuri.org/IDatabaseManager/TagNameAvailableResponse")]
        bool TagNameAvailable(string Name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManager/TagNameAvailable", ReplyAction="http://tempuri.org/IDatabaseManager/TagNameAvailableResponse")]
        System.Threading.Tasks.Task<bool> TagNameAvailableAsync(string Name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManager/AddTag", ReplyAction="http://tempuri.org/IDatabaseManager/AddTagResponse")]
        bool AddTag(AlarmDisplay.ScadaCoreAlarmDisplayReference.Tag tag);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManager/AddTag", ReplyAction="http://tempuri.org/IDatabaseManager/AddTagResponse")]
        System.Threading.Tasks.Task<bool> AddTagAsync(AlarmDisplay.ScadaCoreAlarmDisplayReference.Tag tag);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManager/RemoveTag", ReplyAction="http://tempuri.org/IDatabaseManager/RemoveTagResponse")]
        bool RemoveTag(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManager/RemoveTag", ReplyAction="http://tempuri.org/IDatabaseManager/RemoveTagResponse")]
        System.Threading.Tasks.Task<bool> RemoveTagAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IDatabaseManager/LoadData")]
        void LoadData();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IDatabaseManager/LoadData")]
        System.Threading.Tasks.Task LoadDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManager/GetTagList", ReplyAction="http://tempuri.org/IDatabaseManager/GetTagListResponse")]
        string GetTagList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManager/GetTagList", ReplyAction="http://tempuri.org/IDatabaseManager/GetTagListResponse")]
        System.Threading.Tasks.Task<string> GetTagListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManager/ChangeOTagValue", ReplyAction="http://tempuri.org/IDatabaseManager/ChangeOTagValueResponse")]
        void ChangeOTagValue(string name, double value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManager/ChangeOTagValue", ReplyAction="http://tempuri.org/IDatabaseManager/ChangeOTagValueResponse")]
        System.Threading.Tasks.Task ChangeOTagValueAsync(string name, double value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManager/GetOutputTagList", ReplyAction="http://tempuri.org/IDatabaseManager/GetOutputTagListResponse")]
        string GetOutputTagList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManager/GetOutputTagList", ReplyAction="http://tempuri.org/IDatabaseManager/GetOutputTagListResponse")]
        System.Threading.Tasks.Task<string> GetOutputTagListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManager/GetInputTagList", ReplyAction="http://tempuri.org/IDatabaseManager/GetInputTagListResponse")]
        string GetInputTagList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManager/GetInputTagList", ReplyAction="http://tempuri.org/IDatabaseManager/GetInputTagListResponse")]
        System.Threading.Tasks.Task<string> GetInputTagListAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IDatabaseManager/ChangeScanning")]
        void ChangeScanning(string Name, bool Scanning);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IDatabaseManager/ChangeScanning")]
        System.Threading.Tasks.Task ChangeScanningAsync(string Name, bool Scanning);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManager/GetTagByName", ReplyAction="http://tempuri.org/IDatabaseManager/GetTagByNameResponse")]
        AlarmDisplay.ScadaCoreAlarmDisplayReference.Tag GetTagByName(string Name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManager/GetTagByName", ReplyAction="http://tempuri.org/IDatabaseManager/GetTagByNameResponse")]
        System.Threading.Tasks.Task<AlarmDisplay.ScadaCoreAlarmDisplayReference.Tag> GetTagByNameAsync(string Name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManager/AddAlarm", ReplyAction="http://tempuri.org/IDatabaseManager/AddAlarmResponse")]
        bool AddAlarm(AlarmDisplay.ScadaCoreAlarmDisplayReference.Alarm alarm, string tagID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManager/AddAlarm", ReplyAction="http://tempuri.org/IDatabaseManager/AddAlarmResponse")]
        System.Threading.Tasks.Task<bool> AddAlarmAsync(AlarmDisplay.ScadaCoreAlarmDisplayReference.Alarm alarm, string tagID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManager/GetAlarmList", ReplyAction="http://tempuri.org/IDatabaseManager/GetAlarmListResponse")]
        string GetAlarmList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManager/GetAlarmList", ReplyAction="http://tempuri.org/IDatabaseManager/GetAlarmListResponse")]
        System.Threading.Tasks.Task<string> GetAlarmListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManager/GetAnalogInputList", ReplyAction="http://tempuri.org/IDatabaseManager/GetAnalogInputListResponse")]
        string GetAnalogInputList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManager/GetAnalogInputList", ReplyAction="http://tempuri.org/IDatabaseManager/GetAnalogInputListResponse")]
        System.Threading.Tasks.Task<string> GetAnalogInputListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManager/AlarmNameAvailable", ReplyAction="http://tempuri.org/IDatabaseManager/AlarmNameAvailableResponse")]
        bool AlarmNameAvailable(string Name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManager/AlarmNameAvailable", ReplyAction="http://tempuri.org/IDatabaseManager/AlarmNameAvailableResponse")]
        System.Threading.Tasks.Task<bool> AlarmNameAvailableAsync(string Name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManager/RemoveAlarm", ReplyAction="http://tempuri.org/IDatabaseManager/RemoveAlarmResponse")]
        bool RemoveAlarm(string alarmName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabaseManager/RemoveAlarm", ReplyAction="http://tempuri.org/IDatabaseManager/RemoveAlarmResponse")]
        System.Threading.Tasks.Task<bool> RemoveAlarmAsync(string alarmName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDatabaseManagerChannel : AlarmDisplay.ScadaCoreAlarmDisplayReference.IDatabaseManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DatabaseManagerClient : System.ServiceModel.ClientBase<AlarmDisplay.ScadaCoreAlarmDisplayReference.IDatabaseManager>, AlarmDisplay.ScadaCoreAlarmDisplayReference.IDatabaseManager {
        
        public DatabaseManagerClient() {
        }
        
        public DatabaseManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DatabaseManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DatabaseManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DatabaseManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Registration(string username, string password) {
            return base.Channel.Registration(username, password);
        }
        
        public System.Threading.Tasks.Task<bool> RegistrationAsync(string username, string password) {
            return base.Channel.RegistrationAsync(username, password);
        }
        
        public string Login(string username, string password) {
            return base.Channel.Login(username, password);
        }
        
        public System.Threading.Tasks.Task<string> LoginAsync(string username, string password) {
            return base.Channel.LoginAsync(username, password);
        }
        
        public bool Logout(string token) {
            return base.Channel.Logout(token);
        }
        
        public System.Threading.Tasks.Task<bool> LogoutAsync(string token) {
            return base.Channel.LogoutAsync(token);
        }
        
        public bool TagNameAvailable(string Name) {
            return base.Channel.TagNameAvailable(Name);
        }
        
        public System.Threading.Tasks.Task<bool> TagNameAvailableAsync(string Name) {
            return base.Channel.TagNameAvailableAsync(Name);
        }
        
        public bool AddTag(AlarmDisplay.ScadaCoreAlarmDisplayReference.Tag tag) {
            return base.Channel.AddTag(tag);
        }
        
        public System.Threading.Tasks.Task<bool> AddTagAsync(AlarmDisplay.ScadaCoreAlarmDisplayReference.Tag tag) {
            return base.Channel.AddTagAsync(tag);
        }
        
        public bool RemoveTag(string name) {
            return base.Channel.RemoveTag(name);
        }
        
        public System.Threading.Tasks.Task<bool> RemoveTagAsync(string name) {
            return base.Channel.RemoveTagAsync(name);
        }
        
        public void LoadData() {
            base.Channel.LoadData();
        }
        
        public System.Threading.Tasks.Task LoadDataAsync() {
            return base.Channel.LoadDataAsync();
        }
        
        public string GetTagList() {
            return base.Channel.GetTagList();
        }
        
        public System.Threading.Tasks.Task<string> GetTagListAsync() {
            return base.Channel.GetTagListAsync();
        }
        
        public void ChangeOTagValue(string name, double value) {
            base.Channel.ChangeOTagValue(name, value);
        }
        
        public System.Threading.Tasks.Task ChangeOTagValueAsync(string name, double value) {
            return base.Channel.ChangeOTagValueAsync(name, value);
        }
        
        public string GetOutputTagList() {
            return base.Channel.GetOutputTagList();
        }
        
        public System.Threading.Tasks.Task<string> GetOutputTagListAsync() {
            return base.Channel.GetOutputTagListAsync();
        }
        
        public string GetInputTagList() {
            return base.Channel.GetInputTagList();
        }
        
        public System.Threading.Tasks.Task<string> GetInputTagListAsync() {
            return base.Channel.GetInputTagListAsync();
        }
        
        public void ChangeScanning(string Name, bool Scanning) {
            base.Channel.ChangeScanning(Name, Scanning);
        }
        
        public System.Threading.Tasks.Task ChangeScanningAsync(string Name, bool Scanning) {
            return base.Channel.ChangeScanningAsync(Name, Scanning);
        }
        
        public AlarmDisplay.ScadaCoreAlarmDisplayReference.Tag GetTagByName(string Name) {
            return base.Channel.GetTagByName(Name);
        }
        
        public System.Threading.Tasks.Task<AlarmDisplay.ScadaCoreAlarmDisplayReference.Tag> GetTagByNameAsync(string Name) {
            return base.Channel.GetTagByNameAsync(Name);
        }
        
        public bool AddAlarm(AlarmDisplay.ScadaCoreAlarmDisplayReference.Alarm alarm, string tagID) {
            return base.Channel.AddAlarm(alarm, tagID);
        }
        
        public System.Threading.Tasks.Task<bool> AddAlarmAsync(AlarmDisplay.ScadaCoreAlarmDisplayReference.Alarm alarm, string tagID) {
            return base.Channel.AddAlarmAsync(alarm, tagID);
        }
        
        public string GetAlarmList() {
            return base.Channel.GetAlarmList();
        }
        
        public System.Threading.Tasks.Task<string> GetAlarmListAsync() {
            return base.Channel.GetAlarmListAsync();
        }
        
        public string GetAnalogInputList() {
            return base.Channel.GetAnalogInputList();
        }
        
        public System.Threading.Tasks.Task<string> GetAnalogInputListAsync() {
            return base.Channel.GetAnalogInputListAsync();
        }
        
        public bool AlarmNameAvailable(string Name) {
            return base.Channel.AlarmNameAvailable(Name);
        }
        
        public System.Threading.Tasks.Task<bool> AlarmNameAvailableAsync(string Name) {
            return base.Channel.AlarmNameAvailableAsync(Name);
        }
        
        public bool RemoveAlarm(string alarmName) {
            return base.Channel.RemoveAlarm(alarmName);
        }
        
        public System.Threading.Tasks.Task<bool> RemoveAlarmAsync(string alarmName) {
            return base.Channel.RemoveAlarmAsync(alarmName);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ScadaCoreAlarmDisplayReference.ITrending", CallbackContract=typeof(AlarmDisplay.ScadaCoreAlarmDisplayReference.ITrendingCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface ITrending {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrending/TrendingConnection", ReplyAction="http://tempuri.org/ITrending/TrendingConnectionResponse")]
        string TrendingConnection();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrending/TrendingConnection", ReplyAction="http://tempuri.org/ITrending/TrendingConnectionResponse")]
        System.Threading.Tasks.Task<string> TrendingConnectionAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITrendingCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrending/ITagValueChanged")]
        void ITagValueChanged(string message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITrendingChannel : AlarmDisplay.ScadaCoreAlarmDisplayReference.ITrending, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TrendingClient : System.ServiceModel.DuplexClientBase<AlarmDisplay.ScadaCoreAlarmDisplayReference.ITrending>, AlarmDisplay.ScadaCoreAlarmDisplayReference.ITrending {
        
        public TrendingClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public TrendingClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public TrendingClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public TrendingClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public TrendingClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public string TrendingConnection() {
            return base.Channel.TrendingConnection();
        }
        
        public System.Threading.Tasks.Task<string> TrendingConnectionAsync() {
            return base.Channel.TrendingConnectionAsync();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ScadaCoreAlarmDisplayReference.IRealTimeUnit", SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IRealTimeUnit {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRealTimeUnit/AddressAvailable", ReplyAction="http://tempuri.org/IRealTimeUnit/AddressAvailableResponse")]
        bool AddressAvailable(string address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRealTimeUnit/AddressAvailable", ReplyAction="http://tempuri.org/IRealTimeUnit/AddressAvailableResponse")]
        System.Threading.Tasks.Task<bool> AddressAvailableAsync(string address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRealTimeUnit/RTUIdAvailable", ReplyAction="http://tempuri.org/IRealTimeUnit/RTUIdAvailableResponse")]
        bool RTUIdAvailable(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRealTimeUnit/RTUIdAvailable", ReplyAction="http://tempuri.org/IRealTimeUnit/RTUIdAvailableResponse")]
        System.Threading.Tasks.Task<bool> RTUIdAvailableAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRealTimeUnit/WriteRtuMessage", ReplyAction="http://tempuri.org/IRealTimeUnit/WriteRtuMessageResponse")]
        string WriteRtuMessage(string message, byte[] signature);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRealTimeUnit/WriteRtuMessage", ReplyAction="http://tempuri.org/IRealTimeUnit/WriteRtuMessageResponse")]
        System.Threading.Tasks.Task<string> WriteRtuMessageAsync(string message, byte[] signature);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRealTimeUnit/StopRTU", ReplyAction="http://tempuri.org/IRealTimeUnit/StopRTUResponse")]
        string StopRTU(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRealTimeUnit/StopRTU", ReplyAction="http://tempuri.org/IRealTimeUnit/StopRTUResponse")]
        System.Threading.Tasks.Task<string> StopRTUAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IRealTimeUnit/LeavePublicKey")]
        void LeavePublicKey(string path);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IRealTimeUnit/LeavePublicKey")]
        System.Threading.Tasks.Task LeavePublicKeyAsync(string path);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRealTimeUnitChannel : AlarmDisplay.ScadaCoreAlarmDisplayReference.IRealTimeUnit, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RealTimeUnitClient : System.ServiceModel.ClientBase<AlarmDisplay.ScadaCoreAlarmDisplayReference.IRealTimeUnit>, AlarmDisplay.ScadaCoreAlarmDisplayReference.IRealTimeUnit {
        
        public RealTimeUnitClient() {
        }
        
        public RealTimeUnitClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RealTimeUnitClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RealTimeUnitClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RealTimeUnitClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool AddressAvailable(string address) {
            return base.Channel.AddressAvailable(address);
        }
        
        public System.Threading.Tasks.Task<bool> AddressAvailableAsync(string address) {
            return base.Channel.AddressAvailableAsync(address);
        }
        
        public bool RTUIdAvailable(string id) {
            return base.Channel.RTUIdAvailable(id);
        }
        
        public System.Threading.Tasks.Task<bool> RTUIdAvailableAsync(string id) {
            return base.Channel.RTUIdAvailableAsync(id);
        }
        
        public string WriteRtuMessage(string message, byte[] signature) {
            return base.Channel.WriteRtuMessage(message, signature);
        }
        
        public System.Threading.Tasks.Task<string> WriteRtuMessageAsync(string message, byte[] signature) {
            return base.Channel.WriteRtuMessageAsync(message, signature);
        }
        
        public string StopRTU(string id) {
            return base.Channel.StopRTU(id);
        }
        
        public System.Threading.Tasks.Task<string> StopRTUAsync(string id) {
            return base.Channel.StopRTUAsync(id);
        }
        
        public void LeavePublicKey(string path) {
            base.Channel.LeavePublicKey(path);
        }
        
        public System.Threading.Tasks.Task LeavePublicKeyAsync(string path) {
            return base.Channel.LeavePublicKeyAsync(path);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ScadaCoreAlarmDisplayReference.IAlarmDisplay", CallbackContract=typeof(AlarmDisplay.ScadaCoreAlarmDisplayReference.IAlarmDisplayCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IAlarmDisplay {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlarmDisplay/AlarmDisplayConnection", ReplyAction="http://tempuri.org/IAlarmDisplay/AlarmDisplayConnectionResponse")]
        string AlarmDisplayConnection();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlarmDisplay/AlarmDisplayConnection", ReplyAction="http://tempuri.org/IAlarmDisplay/AlarmDisplayConnectionResponse")]
        System.Threading.Tasks.Task<string> AlarmDisplayConnectionAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAlarmDisplayCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAlarmDisplay/DisplayAlarm")]
        void DisplayAlarm(string message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAlarmDisplayChannel : AlarmDisplay.ScadaCoreAlarmDisplayReference.IAlarmDisplay, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AlarmDisplayClient : System.ServiceModel.DuplexClientBase<AlarmDisplay.ScadaCoreAlarmDisplayReference.IAlarmDisplay>, AlarmDisplay.ScadaCoreAlarmDisplayReference.IAlarmDisplay {
        
        public AlarmDisplayClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public AlarmDisplayClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public AlarmDisplayClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public AlarmDisplayClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public AlarmDisplayClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public string AlarmDisplayConnection() {
            return base.Channel.AlarmDisplayConnection();
        }
        
        public System.Threading.Tasks.Task<string> AlarmDisplayConnectionAsync() {
            return base.Channel.AlarmDisplayConnectionAsync();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ScadaCoreAlarmDisplayReference.IReportManager", SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IReportManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportManager/ReportAlarmsInPeriod", ReplyAction="http://tempuri.org/IReportManager/ReportAlarmsInPeriodResponse")]
        string ReportAlarmsInPeriod(System.DateTime start, System.DateTime end);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportManager/ReportAlarmsInPeriod", ReplyAction="http://tempuri.org/IReportManager/ReportAlarmsInPeriodResponse")]
        System.Threading.Tasks.Task<string> ReportAlarmsInPeriodAsync(System.DateTime start, System.DateTime end);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportManager/ReportAlarmsWithSelectedPriority", ReplyAction="http://tempuri.org/IReportManager/ReportAlarmsWithSelectedPriorityResponse")]
        string ReportAlarmsWithSelectedPriority(int priority);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportManager/ReportAlarmsWithSelectedPriority", ReplyAction="http://tempuri.org/IReportManager/ReportAlarmsWithSelectedPriorityResponse")]
        System.Threading.Tasks.Task<string> ReportAlarmsWithSelectedPriorityAsync(int priority);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportManager/ReportTagValueChangesInPeriod", ReplyAction="http://tempuri.org/IReportManager/ReportTagValueChangesInPeriodResponse")]
        string ReportTagValueChangesInPeriod(System.DateTime start, System.DateTime end);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportManager/ReportTagValueChangesInPeriod", ReplyAction="http://tempuri.org/IReportManager/ReportTagValueChangesInPeriodResponse")]
        System.Threading.Tasks.Task<string> ReportTagValueChangesInPeriodAsync(System.DateTime start, System.DateTime end);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportManager/ReportLastAnalogInputValues", ReplyAction="http://tempuri.org/IReportManager/ReportLastAnalogInputValuesResponse")]
        string ReportLastAnalogInputValues();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportManager/ReportLastAnalogInputValues", ReplyAction="http://tempuri.org/IReportManager/ReportLastAnalogInputValuesResponse")]
        System.Threading.Tasks.Task<string> ReportLastAnalogInputValuesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportManager/ReportLastDigitalInputValues", ReplyAction="http://tempuri.org/IReportManager/ReportLastDigitalInputValuesResponse")]
        string ReportLastDigitalInputValues();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportManager/ReportLastDigitalInputValues", ReplyAction="http://tempuri.org/IReportManager/ReportLastDigitalInputValuesResponse")]
        System.Threading.Tasks.Task<string> ReportLastDigitalInputValuesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportManager/ReportValuesOfSelectedID", ReplyAction="http://tempuri.org/IReportManager/ReportValuesOfSelectedIDResponse")]
        string ReportValuesOfSelectedID(string ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportManager/ReportValuesOfSelectedID", ReplyAction="http://tempuri.org/IReportManager/ReportValuesOfSelectedIDResponse")]
        System.Threading.Tasks.Task<string> ReportValuesOfSelectedIDAsync(string ID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReportManagerChannel : AlarmDisplay.ScadaCoreAlarmDisplayReference.IReportManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReportManagerClient : System.ServiceModel.ClientBase<AlarmDisplay.ScadaCoreAlarmDisplayReference.IReportManager>, AlarmDisplay.ScadaCoreAlarmDisplayReference.IReportManager {
        
        public ReportManagerClient() {
        }
        
        public ReportManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReportManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ReportAlarmsInPeriod(System.DateTime start, System.DateTime end) {
            return base.Channel.ReportAlarmsInPeriod(start, end);
        }
        
        public System.Threading.Tasks.Task<string> ReportAlarmsInPeriodAsync(System.DateTime start, System.DateTime end) {
            return base.Channel.ReportAlarmsInPeriodAsync(start, end);
        }
        
        public string ReportAlarmsWithSelectedPriority(int priority) {
            return base.Channel.ReportAlarmsWithSelectedPriority(priority);
        }
        
        public System.Threading.Tasks.Task<string> ReportAlarmsWithSelectedPriorityAsync(int priority) {
            return base.Channel.ReportAlarmsWithSelectedPriorityAsync(priority);
        }
        
        public string ReportTagValueChangesInPeriod(System.DateTime start, System.DateTime end) {
            return base.Channel.ReportTagValueChangesInPeriod(start, end);
        }
        
        public System.Threading.Tasks.Task<string> ReportTagValueChangesInPeriodAsync(System.DateTime start, System.DateTime end) {
            return base.Channel.ReportTagValueChangesInPeriodAsync(start, end);
        }
        
        public string ReportLastAnalogInputValues() {
            return base.Channel.ReportLastAnalogInputValues();
        }
        
        public System.Threading.Tasks.Task<string> ReportLastAnalogInputValuesAsync() {
            return base.Channel.ReportLastAnalogInputValuesAsync();
        }
        
        public string ReportLastDigitalInputValues() {
            return base.Channel.ReportLastDigitalInputValues();
        }
        
        public System.Threading.Tasks.Task<string> ReportLastDigitalInputValuesAsync() {
            return base.Channel.ReportLastDigitalInputValuesAsync();
        }
        
        public string ReportValuesOfSelectedID(string ID) {
            return base.Channel.ReportValuesOfSelectedID(ID);
        }
        
        public System.Threading.Tasks.Task<string> ReportValuesOfSelectedIDAsync(string ID) {
            return base.Channel.ReportValuesOfSelectedIDAsync(ID);
        }
    }
}
